# [ezequielv] old? (see: https://github.com/jekyll/jekyll/issues/4145#issuecomment-158140960)
# prev: # This is the default format.
# prev: # For more see: http://jekyllrb.com/docs/permalinks/
# prev: permalink: /:categories/:year/:month/:day/:title

#+? exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "lftp-*.cfg", "modules", "modules/pub", "common", "common/src"]
exclude:
  - ".rvmrc"
  - ".rbenv-version"
  - ".local[-_]*"
  - ".github/"
  - "lftp-*.cfg"
  # this is a directory
  #? NOTE: error when serving '/index.html':
  #?  ref: [2020-06-03 00:22:59] ERROR `/images/bgs/body.png' not found.
  #? - "local/"
  - "local/"
  # is this excluded because it starts with a '.', or because the wildcard has actually worked?
  - ".editorconfig*"
  # standard jekyll/JB components
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "modules"
  #+ not_needed: - "modules/pub"
  - "common"
  #+ not_needed: - "common/src"
  - "tags.temp"
  - "tags.lock"
  #-? does jekyll support wildcards? # - "ctags_tags*"
  - "ctags_tags.lock"
  - "ctags_tags.temp"
  - "ctags_tags"

# NOTE: implemented by '{common}/_plugins/jekyll-watcher-override.rb'
exclude_from_watch:
  #? # NOTE: removed: we don't want the 'tags' source page to not be watched.
  #? # - tags
  #? - "tags.temp"
  #? - "tags.lock"
  #? 2020.12.09: # NOTE: decided to leave this entry, as I don't like the unnecessary regeneration messages
  #? 2020.12.09: #  (and the 'tags' page does not change often/at all)
  #? 2020.12.09: - tags
  #? - modules/
  #? - common/
  #? - common/root
  #? - common/src
  #? - common/src/
  #? - modules/
  #? - modules/pub/
  #? - modules/pub/ev-site-jb-common-01
  #? - common/src/jb-common-01/
  #? - common/src/jb-common-01/_plugins
  #? - common/src/jb-common-01/_posts
  #? - common/src/jb-common-01/_posts/core-samples
  #? - _posts/core-samples/
  #? - _plugins/
  #? - common/root/_plugins/
  #? - modules/pub/ev-site-jb-common-01/
  #? - modules/pub/ev-site-jb-common-01/_plugins/

# [ezequielv] not supported: highlighter: pygments
#  see: https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors
#  see: https://help.github.com/articles/troubleshooting-jekyll-builds
highlighter: rouge

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : ezequielv's blog
tagline: Tech stuff
author :
  name : Ezequiel Valenzuela
  email : evp.dev.ezequiel.p.01@jev.me.uk
  github : ezequielv
  twitter : ezeuk
  feedburner : ezeblogtech

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
#production_url : http://username.github.io
# 2020.12.04: testing CNAME support now: #+ production_url : https://ezequielv.github.io/blog-tech
#+? production_url : https://www1.jev.me.uk
production_url : https://blog-b1.jev.me.uk

# NOTE: ref: https://github.com/philnash/jekyll-gzip#installation
#  plugins:
#    - jekyll-gzip
#+ prev: v1: gems: ["jekyll-sitemap"]
# 2020.12.09: Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
# 2020.12.09: gems:
plugins:
  - "jekyll-sitemap"
  - "jekyll-gzip"

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.3.0

  # All links will be namespaced by BASE_PATH if defined.
  # Links in your website should always be prefixed with {{BASE_PATH}}
  # however this value will be dynamically changed depending on your deployment situation.
  #
  # CNAME (http://yourcustomdomain.com)
  #   DO NOT SET BASE_PATH
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Pages (http://username.github.io)
  #   DO NOT SET BASE_PATH
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Project Pages (http://username.github.io/project-name)
  #
  #   A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
  #  REQUIRED! Set BASE_PATH to: http://username.github.io/project-name
  #
  # CAUTION:
  #   - When in Localhost, your site will run from root "/" regardless of BASE_PATH
  #   - Only the following values are falsy: ["", null, false]
  #   - When setting BASE_PATH it must be a valid url.
  #     This means always setting the protocol (http|https) or prefixing with "/"
  #BASE_PATH : false
  # [ezequielv] github pages: BASE_PATH : https://ezequielv.github.io/blog-tech
  # 2020.12.04: testing CNAME support now: BASE_PATH : /blog-tech
  BASE_PATH : ""

  # By default, the asset_path is automatically defined relative to BASE_PATH plus the enabled theme.
  # ex: [BASE_PATH]/assets/themes/[THEME-NAME]
  #
  # Override this by defining an absolute path to assets here.
  # ex:
  #   http://s3.amazonaws.com/yoursite/themes/watermelon
  #   /assets
  #
  ASSET_PATH : false

  # These paths are to the main pages Jekyll-Bootstrap ships with.
  # Some JB helpers refer to these paths; change them here if needed.
  #
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  # Settings for comments helper
  # Set 'provider' to the comment provider you want to use.
  # Set 'provider' to false to turn commenting off globally.
  #
  comments :
    provider : disqus
    disqus :
      # orig: short_name : jekyllbootstrap
      short_name : ezequielv-blog-tech
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light
    duoshuo :
      short_name : jekyllbootstrap

  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #
  analytics :
    provider : google
    gauges :
        site_id : 'SITE ID'
    google :
        tracking_id : 'UA-123-12'
    getclicky :
      site_id :
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik

  # Settings for sharing helper.
  # Sharing is for things like tweet, plusone, like, reddit buttons etc.
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing :
    provider : false

  # Settings for all other include helpers can be defined by creating
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.

  # _includes/JB/include_module_optional support
  include_module_optional :
    #+ debug : true
    include_definitions :
      group_0 :
        -
          module : "JB/some_other_module_1"
          includes : ["some_include_file_1", "some_include_file_2"]
        -
          module : "JB/comments"
          includes : ["begin_enabled", "mid_beforeprovider"]
        -
          module : "JB/some_other_module_2"
          includes : ["some_include_file_1", "some_include_file_2"]

# see also: https://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults :
  -
    scope :
      path : ""
    values :
      comments_config :
        # This sets the variable jb_comment_id
        # type:
        #   - string with an id from the list below; or
        #   - list of strings, where each string is an id from the list below;
        #
        # supported ids:
        #  - "none", nil or unset: leave unset;
        #  - "auto": try to use, in order: "ident", "relurl"
        #  - "ident": identifiers only: try to use, in order: "commentid", "pageid"
        #  - "commentid": use 'page.comment_id';
        #  - "pageid": use 'page.id';
        #  - "relurl": relative url ('page.url') (does not include BASE_PATH);
        var_id_ident_method : auto
        # This sets the variable jb_comment_url
        # possible values: falsy (nil, false, unset), truthy (anything else);
        var_url_enable : true
        # If set, comments are only shown when the "production" mode has the specified value:
        #   - "prod": production only;
        #   - "dev": development only;
        #   - "any" (default): always enabled;
        on_prod_mode : prod
      test_subkey :
        value_string : string_value
        value_array : ["array_item_1", "array_item_2"]
  # note: github now published as static pages (not using configuration-less site building)
  # [ezequielv] based on https://github.com/jekyll/jekyll/issues/4145#issuecomment-158140960 {{{
  # values for "dumb" site hosting (where the suffix are needed)
  # note: [*.]freeserverhost.com works well with this
  -
    scope:
      type: pages
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      type: posts
    values:
      # idea: permalink: /:year/:month/:day/:title
      # 2020.12.09: (used when github built pages itself) permalink: /:categories/:year/:month/:day/:title
      permalink: /:categories/:year/:month/:day/:title:output_ext

