#!/bin/sh
set -e

# boilerplate {{{
. "${0%/*}/../common/common_functions.sh" || exit $?
f_standard_init
# }}}

[ -d "${JEKYLLDEPLOY_HOOKS_SITECONTENT_PREV_DIR}/" ] \
	|| f_abort "directory '${JEKYLLDEPLOY_HOOKS_SITECONTENT_PREV_DIR}' does not exist.  another script sould have populated that directory before this point."

# MAYBE: use 'exec'? (but that would not execute the 'EXIT' trap handler)
f_cmd_run \
	"${0%/*}/../common/local-bin-dir/site_keep_previously_compressed_if_source_unchanged" \
		--verbose \
		--prev-dir="${JEKYLLDEPLOY_HOOKS_SITECONTENT_PREV_DIR}" \
		--build-dir="${JEKYLLDEPLOY_HOOKS_SITECONTENT_BUILD_DIR}" \
	# end

